apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  lables:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLables:
      app: nginx

  template:
    metadata:
      lables:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80